# Generated by Django 6.1.1 on 2026-09-25 14:07

import django.db.models.deletion
import uuid
import verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_raw_text', models.CharField(help_text="Expiry exactly as printed on the package, e.g. '08/2027'", max_length=50)),
                ('expiry_precision', models.CharField(choices=[('day', 'Exact day printed'), ('month', 'Month and year only')], max_length=10)),
                ('expiry_date', models.DateField(help_text='Computed per ADR 0003; used for all comparisons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='verification.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('strength', models.CharField(help_text="e.g. '500 mg'", max_length=100)),
                ('dosage_form', models.CharField(blank=True, help_text="e.g. 'tablet', 'capsule', 'syrup'", max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'manufacturer', 'strength', 'dosage_form'), name='unique_product_identity')],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='verification.product'),
        ),
        migrations.CreateModel(
            name='ProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.TextField(help_text="Where this reference came from, e.g. 'Manufacturer packaging insert, photographed 2026-09-20'")),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='reference_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='verification.product')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField()),
                ('extractor_name', models.CharField(help_text="Which extractor produced extracted_data, e.g. 'qwen-vision' or 'stub-v1'", max_length=100)),
                ('result_category', models.CharField(choices=[('verified', 'Information verified'), ('warning', 'Potential warning signs'), ('unverifiable', 'Could not verify'), ('expiry_warning', 'Expiry warning')], max_length=20)),
                ('evidence', models.JSONField(default=list, help_text='List of short evidence strings backing result_category')),
                ('confirmed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='verification.batch')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='verification.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=verification.models.verification_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='verification.verificationrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_batch_per_product'),
        ),
    ]
