# Generated by Django 6.1.1 on 2026-09-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='swahili_audio',
            field=models.FileField(blank=True, null=True, upload_to='verification_audio/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='swahili_text',
            field=models.TextField(blank=True, default='', help_text='Qwen translation of extracted_data.printed_instructions'),
        ),
    ]
